"""
Task 5(a) — LLM-driven multi-document summarization for the Employment &
Career category (same category and same 500-post sample as Task 4, per
the brief's instruction to summarize "a specific category identified in
Task 4(a)").

500 posts is too much to put in one prompt, so this uses hierarchical
map-reduce summarization:

  MAP     : 500 posts, in batches of 20 (25 batches)  -> 25 batch summaries
  REDUCE 1: 25 batch summaries, in groups of 5 (5 groups) -> 5 cluster summaries
  REDUCE 2: 5 cluster summaries + aggregate stats (computed directly from
            Task 4's extractions.csv, not by the LLM) -> one final
            multi-stakeholder summary

The aggregate stats (post_intent distribution, top skills/locations,
employment-type mix, salary/company mention rates) are computed with
plain pandas, not generated by the model, and are the ONLY numbers the
final-reduce prompt is allowed to cite — this is what makes Task 5(b)'s
factual-consistency check (evaluate_summary.py) possible: any number in
the final summary that doesn't trace back to this stats block is a
fabrication by construction, not a judgment call.
"""
import json
import re
import warnings
from collections import Counter
from pathlib import Path

import pandas as pd
import torch
from transformers import pipeline
from transformers.utils import logging as hf_logging

hf_logging.set_verbosity_error()
warnings.filterwarnings("ignore")

# ── Config ────────────────────────────────────────────────────────────────────
MODEL_NAME = "microsoft/Phi-3-mini-4k-instruct"   # same model as task4 — proven reliable instruction-follower
POSTS_PER_BATCH = 20     # map stage
SUMMARIES_PER_GROUP = 5  # reduce-1 stage
POST_TRUNCATE_WORDS = 60
MAX_NEW_TOKENS_MAP = 120
MAX_NEW_TOKENS_CLUSTER = 150
MAX_NEW_TOKENS_FINAL = 650
TOP_N = 10

BASE = Path(__file__).parent
EXTRACTIONS_CSV = BASE.parent / "task4-extraction" / "results" / "extractions.csv"
OUT_DIR = BASE / "results"
PLOT_DIR = BASE / "plots"
OUT_DIR.mkdir(parents=True, exist_ok=True)
PLOT_DIR.mkdir(parents=True, exist_ok=True)


def get_device():
    if torch.cuda.is_available():
        return 0
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps"
    return -1


def truncate_words(text, n):
    return " ".join(str(text).split()[:n])


def extract_response_text(item):
    entry = item[0] if isinstance(item, list) else item
    convo = entry["generated_text"]
    return str(convo[-1]["content"]).strip() if isinstance(convo, list) else str(convo).strip()


def generate(pipe, messages_list, max_new_tokens, batch_size=4, tag=""):
    responses = []
    n = len(messages_list)
    for start in range(0, n, batch_size):
        chunk = messages_list[start:start + batch_size]
        outputs = pipe(chunk, max_new_tokens=max_new_tokens, do_sample=False,
                        pad_token_id=pipe.tokenizer.pad_token_id)
        responses.extend(extract_response_text(o) for o in outputs)
        if (start // batch_size) % 5 == 0:
            print(f"  {tag}{min(start + batch_size, n)}/{n}")
    return responses


# ── Aggregate stats (computed directly, not by the LLM) ─────────────────────────
def compute_stats(df):
    n = len(df)
    intent_counts = df["post_intent"].value_counts()
    intent_pct = {k: round(100 * v / n, 1) for k, v in intent_counts.items()}

    emp_type_counts = df["employment_type"].dropna().str.lower().value_counts()
    top_emp_types = emp_type_counts.head(5).to_dict()
    other_emp = int(emp_type_counts.iloc[5:].sum()) if len(emp_type_counts) > 5 else 0

    skills = Counter()
    for s in df["skills"].dropna():
        for sk in json.loads(s):
            skills[sk.lower()] += 1

    locations = Counter(df["location"].dropna().str.lower())

    stats = {
        "n_posts": n,
        "post_intent_pct": intent_pct,
        "top_employment_types": top_emp_types,
        "other_employment_type_count": other_emp,
        "top_skills": skills.most_common(TOP_N),
        "top_locations": locations.most_common(TOP_N),
        "salary_mentioned_pct": round(100 * df["salary"].notna().sum() / n, 1),
        "company_mentioned_pct": round(100 * df["company"].notna().sum() / n, 1),
        "job_posting_pct": intent_pct.get("job_posting", 0.0),
        "seeking_job_pct": intent_pct.get("seeking_job", 0.0),
    }
    return stats


def format_stats_block(stats):
    lines = [f"Total posts analyzed: {stats['n_posts']}", ""]
    lines.append("Post intent breakdown:")
    for k, v in stats["post_intent_pct"].items():
        lines.append(f"  - {k}: {v}%")
    lines.append("")
    lines.append("Most common employment types mentioned (when stated):")
    for k, v in stats["top_employment_types"].items():
        lines.append(f"  - {k}: {v} posts")
    lines.append("")
    lines.append(f"Top skills/tools mentioned: {', '.join(f'{s} ({c})' for s, c in stats['top_skills'][:8])}")
    lines.append(f"Top locations mentioned: {', '.join(f'{l} ({c})' for l, c in stats['top_locations'][:8])}")
    lines.append("")
    lines.append(f"Salary explicitly mentioned in {stats['salary_mentioned_pct']}% of posts")
    lines.append(f"A specific company named in {stats['company_mentioned_pct']}% of posts")
    lines.append(f"Only {stats['job_posting_pct']}% of posts are actual job postings — "
                  f"{stats['seeking_job_pct']}% are people seeking jobs/advice instead")
    return "\n".join(lines)


# ── Prompts ───────────────────────────────────────────────────────────────────
MAP_SYSTEM = (
    "You are analyzing a batch of real Reddit posts from r/srilanka about jobs and careers. "
    "Write a factual 3-4 sentence summary of the common themes, concerns, and notable patterns "
    "in ONLY the posts given below. Do not invent statistics, do not generalize beyond what "
    "these specific posts say, and do not mention information not present in the text."
)

CLUSTER_SYSTEM = (
    "You are combining several short summaries of Reddit posts about jobs and careers in Sri "
    "Lanka into one consolidated summary. Write a factual 3-5 sentence summary capturing the "
    "themes that recur across the summaries below. Do not invent new statistics or information "
    "not present in the summaries."
)

FINAL_SYSTEM = """You are producing a multi-stakeholder insight report from an analysis of r/srilanka job/career posts, for job seekers, employers, and policymakers.

You are given (1) verified statistics from the full analyzed sample, and (2) consolidated theme summaries from that sample. Use ONLY the statistics given below verbatim — do not invent, round differently, or alter any number or percentage. If you are not given a number for something, describe it qualitatively (e.g. "several posts...") instead of making one up.

Write the report in this exact Markdown structure:

## Overview
(2-3 sentences on the overall picture)

## For Job Seekers
(3-4 actionable bullet points)

## For Employers & Recruiters
(3-4 actionable bullet points)

## For Policymakers
(3-4 actionable bullet points, e.g. on skills gaps, youth employment, migration)
"""


def build_map_messages(batch_texts):
    numbered = "\n\n".join(f"{i+1}. {truncate_words(t, POST_TRUNCATE_WORDS)}" for i, t in enumerate(batch_texts))
    return [{"role": "system", "content": MAP_SYSTEM}, {"role": "user", "content": numbered}]


def build_cluster_messages(summaries):
    numbered = "\n\n".join(f"{i+1}. {s}" for i, s in enumerate(summaries))
    return [{"role": "system", "content": CLUSTER_SYSTEM}, {"role": "user", "content": numbered}]


def build_final_messages(stats_block, cluster_summaries):
    user = (
        f"VERIFIED STATISTICS:\n{stats_block}\n\n"
        f"CONSOLIDATED THEME SUMMARIES:\n" + "\n\n".join(f"- {s}" for s in cluster_summaries)
    )
    return [{"role": "system", "content": FINAL_SYSTEM}, {"role": "user", "content": user}]


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    device = get_device()
    print(f"Device : {device}")
    print(f"PyTorch: {torch.__version__}")

    df = pd.read_csv(EXTRACTIONS_CSV)
    df = df[df["parse_success"] == True].reset_index(drop=True)  # noqa: E712
    print(f"Loaded {len(df):,} successfully-parsed Employment & Career extractions")

    print("\nComputing aggregate stats (pandas, not LLM-generated) …")
    stats = compute_stats(df)
    stats_block = format_stats_block(stats)
    print(stats_block)
    with open(OUT_DIR / "aggregate_stats.json", "w") as f:
        json.dump(stats, f, indent=2)

    dtype = torch.float16 if device != -1 else torch.float32
    print(f"\nLoading {MODEL_NAME} …")
    pipe = pipeline("text-generation", model=MODEL_NAME, torch_dtype=dtype, device=device, batch_size=4)
    if pipe.tokenizer.pad_token_id is None:
        pipe.tokenizer.pad_token = pipe.tokenizer.eos_token

    # ── MAP ────────────────────────────────────────────────────────────────
    texts = df["clean_text"].tolist()
    batches = [texts[i:i + POSTS_PER_BATCH] for i in range(0, len(texts), POSTS_PER_BATCH)]
    print(f"\nMAP: {len(batches)} batches of up to {POSTS_PER_BATCH} posts …")
    map_messages = [build_map_messages(b) for b in batches]
    batch_summaries = generate(pipe, map_messages, MAX_NEW_TOKENS_MAP, batch_size=4, tag="  batch ")
    with open(OUT_DIR / "batch_summaries.json", "w") as f:
        json.dump(batch_summaries, f, indent=2)

    # ── REDUCE 1 (cluster) ────────────────────────────────────────────────────
    groups = [batch_summaries[i:i + SUMMARIES_PER_GROUP] for i in range(0, len(batch_summaries), SUMMARIES_PER_GROUP)]
    print(f"\nREDUCE-1: {len(groups)} groups of up to {SUMMARIES_PER_GROUP} batch summaries …")
    cluster_messages = [build_cluster_messages(g) for g in groups]
    cluster_summaries = generate(pipe, cluster_messages, MAX_NEW_TOKENS_CLUSTER, batch_size=4, tag="  group ")
    with open(OUT_DIR / "cluster_summaries.json", "w") as f:
        json.dump(cluster_summaries, f, indent=2)

    # ── REDUCE 2 (final) ──────────────────────────────────────────────────────
    print("\nREDUCE-2: final multi-stakeholder summary …")
    final_messages = [build_final_messages(stats_block, cluster_summaries)]
    final_summary = generate(pipe, final_messages, MAX_NEW_TOKENS_FINAL, batch_size=1, tag="  final ")[0]

    with open(OUT_DIR / "final_summary.md", "w") as f:
        f.write(f"# Task 5(a) — Employment & Career: Multi-Document Summary\n\n")
        f.write(f"*Generated by {MODEL_NAME} from {stats['n_posts']} posts via hierarchical "
                f"map-reduce summarization ({len(batches)} batches -> {len(groups)} clusters -> 1 final report).*\n\n")
        f.write(final_summary)
        f.write("\n\n---\n\n## Verified statistics used for grounding\n\n```\n")
        f.write(stats_block)
        f.write("\n```\n")

    print("\n" + "=" * 60)
    print(final_summary)
    print("=" * 60)

    print(f"\nResults → {OUT_DIR}")
    print("Task 5(a) summarization complete ✓")


if __name__ == "__main__":
    main()
